<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <PropertyGroup>
    <RootNamespace>MassTransit</RootNamespace>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>MassTransit.WebApi</PackageId>
    <Title>MassTransit.WebApi</Title>
    <PackageTags>MassTransit;WebApi</PackageTags>
    <Description>MassTransit WebApi transport support; $(Description)</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.1.1" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MassTransit\MassTransit.csproj" />
  </ItemGroup>
</Project>
